Feature/fisrt step basic appservice
Azure-Samples/app-service-baseline-implementation pull request #5
Opened 2023-08-11 16:36 UTC by v-fearam

## Purpose
Moving Sample application to its own repository
Improve readme file to make it easier to deploy and fix some issues in the instructions.

## Does this introduce a breaking change?

```
[ x] Yes
[ ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ x] Refactoring (no functional changes, no api changes)
[ x] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
Complete deploy end to end, following readme instructions. It includes validations.

2023-08-11 16:49 UTC, v-fearam commented
#assign-reviewer:josevarela

2023-08-14 14:38 UTC, josevarela requested changes
Looks good. A couple of suggestions in-line

2023-08-14 14:38 UTC, josevarela commented on README.md
> +1. It is needed an user with [roles](https://learn.microsoft.com/azure/role-based-access-control/built-in-roles) with enough permission to do role assigments. For example User Access Administrator or
```suggestion
1. The deployment must be started by a user who has sufficient permissions to assign [roles](https://learn.microsoft.com/azure/role-based-access-control/built-in-roles), such as a User Access Administrator or Owner.
```

2023-08-14 14:38 UTC, josevarela commented on README.md
> +   BASE_NAME=<base-resource-name between 3 and 6 charcters>
```suggestion
   BASE_NAME=<base-resource-name (between 3 and 6 characters)>

```

2023-08-14 14:38 UTC, josevarela commented on README.md
> +clone https://github.com/Azure-Samples/app-service-sample-workload.git
git clone(?)

```suggestion
git clone https://github.com/Azure-Samples/app-service-sample-workload.git

```

2023-08-18 14:53 UTC, josevarela requested changes
Looks good. One small suggestion to rename a variable in-line

2023-08-18 14:53 UTC, josevarela commented on README.md
>  NAME_OF_WEST_STORAGE_ACCOUNT="$STORAGE_ACCOUNT_PREFIX$BASE_NAME"
Can we rename this variable to remove WEST from the name? Maybe just NAME_OF_STORAGE_ACCOUNT

2023-08-18 16:07 UTC, v-fearam commented on README.md
>  NAME_OF_WEST_STORAGE_ACCOUNT="$STORAGE_ACCOUNT_PREFIX$BASE_NAME"
done

2023-08-18 18:19 UTC, josevarela approved these changes
Looks good!

2023-08-18 18:50 UTC, merged